# Generated by Django 3.2.25 on 2025-09-06 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan3DJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_file', models.FileField(upload_to='inputs/')),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='inputs/rasterized/')),
                ('detections_json', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('glb_model', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan3d_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
