# Generated by Django 5.2.5 on 2025-09-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan3DJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_file', models.FileField(upload_to='inputs/')),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='inputs/rasterized/')),
                ('detections_json', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('glb_model', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
    ]
