# Generated by Django 3.2.25 on 2025-09-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan3djob',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan3d_jobs', to='users.usuario'),
        ),
    ]
